using System.Reflection;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.1.0.0")]
[assembly: AssemblyCompanyAttribute("Paraesthesia")]
[assembly: AssemblyCopyrightAttribute("(c) 2007 - 2007 Travis Illig")]

